name: ci_cmake
env:
  CI: true

on:
  push:
    paths:
      - "**/*.f90"
      - "**/*.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/ci_cmake.yml"

jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - run: cmake -B build
      env:
        FC: gfortran-9

    - run: cmake --build build --parallel

    - run: ctest -V
      working-directory: build

  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - run: cinst -y ninja

    - run: cmake -B build -G Ninja
      env:
        FC: gfortran

    - run: cmake --build build --parallel

    - run: ctest -V
      working-directory: build
