name: ci_cmake

env:
  CMAKE_BUILD_TYPE: Release

on:
  push:
    paths:
      - "**/*.f90"
      - "**/*.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/ci_cmake.yml"

jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - run: cmake -B build
    - run: cmake --build build --parallel

    - run: ctest --test-dir build
